spring:
    application:
        name: ms-consumidor
    threads:
        virtual:
            enabled: false
    datasource:
        username: teste
        password: postgres
        url: jdbc:postgresql://localhost:5432/ms-consumidor
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
logging:
    level:
        root: info
        br.com.messagedispatcher: debug
        org.springframework.boot.autoconfigure: info
#        sql: debug
message:
    dispatcher:
        mapped:
            headers: x-api-key, x-flowId, x-traceId, x-no-exist
        prefetch-count: 20
        max-retry-attempts: 3
        reply-timeout: 15000
        # returnExceptions: true
        username: guest
        concurrency: 1-10
        entity-events:
          enabled: false
        logging:
            message-router:
                enabled: true