spring:
    application:
        name: ms-consumidor
    threads:
        virtual:
            enabled: false
    datasource:
        username: sa
        password: password
        url: jdbc:h2:mem:ms-consumidor
        driverClassName: org.h2.Driver
logging:
    level:
        root: info
        br.com.messagedispatcher: debug
        org.springframework.boot.autoconfigure: info
        sql: debug
message:
    dispatcher:
        mapped:
            headers: x-api-key, x-flowId, x-traceId, x-no-exist
        prefetch-count: 20
        max-retry-attempts: 3
        reply-timeout: 15000
        # returnExceptions: true
        username: guest
        concurrency: 1-10
